#!/usr/bin/env bash
# Build a native Arch package (.pkg.tar.zst) installable with `sudo pacman -U`.
#
# Usage: make-arch-pkg.sh <version> [arch]   (run AFTER make-tarball.sh)
#
# This is the PREBUILT, SELF-CONTAINED counterpart to arch/PKGBUILD:
#
#   arch/PKGBUILD      source recipe for the AUR. `makepkg -si` compiles from
#                      source against the system LLVM (depends on llvm-libs).
#   make-arch-pkg.sh   wraps the portable tarball — which already bundles the
#                      full LLVM shared-library closure and the ntsc runtime —
#                      into a binary package. No compile, no source download,
#                      and no dependency on the system LLVM version, so it keeps
#                      working when rolling Arch bumps LLVM to a new soname.
#
# It reuses dist/ntsc-<version>-linux-<arch>.tar.gz, so run make-tarball.sh
# first. Requires makepkg, which only runs on Arch and refuses to run as root;
# CI runs this inside an archlinux container as an unprivileged build user.
set -euo pipefail

VERSION="${1:?usage: make-arch-pkg.sh <version> [arch]}"
ARCH="${2:-$(uname -m)}"
TARBALL="ntsc-$VERSION-linux-$ARCH.tar.gz"

if [ ! -f "dist/$TARBALL" ]; then
  echo "error: dist/$TARBALL not found - run make-tarball.sh $VERSION first" >&2
  exit 1
fi
if ! command -v makepkg >/dev/null 2>&1; then
  echo "error: makepkg not found - this script must run on Arch Linux" >&2
  exit 1
fi
if [ "$(id -u)" = "0" ]; then
  echo "error: makepkg refuses to run as root - run as an unprivileged user" >&2
  exit 1
fi

# makepkg copies a local source from the PKGBUILD's own directory and writes
# its output there, so stage both in a scratch dir under the gitignored dist/.
BUILD="dist/.arch-build"
rm -rf "$BUILD"
mkdir -p "$BUILD"
cp "dist/$TARBALL" "$BUILD/$TARBALL"

# @VERSION@/@ARCH@ are substituted below; $pkgver, $srcdir and $pkgdir are left
# literal for makepkg to expand. options: keep the prebuilt payload byte-for-
# byte — !strip protects libntsc_runtime.a's symbol table (stripping it breaks
# linking) and the bundled .so RUNPATHs; staticlibs keeps the .a; !debug skips
# debug-symbol extraction (there are no build sources); !zipman leaves the
# already-gzipped man page alone.
cat > "$BUILD/PKGBUILD" <<'PKGBUILD_EOF'
# Maintainer: yasakei
# Prebuilt, self-contained binary package. Bundles the LLVM shared-library
# closure and the ntsc runtime under /usr/lib/ntsc, so it installs and runs
# with no system LLVM dependency. Generated by make-arch-pkg.sh from the
# portable tarball; see PKGBUILD for the source-based AUR recipe.
pkgname=ntsc
pkgver=@VERSION@
pkgrel=1
pkgdesc="Neutron Type-Safe Compiler: a statically typed, memory-safe systems language compiled through LLVM (self-contained; bundles LLVM)"
arch=('@ARCH@')
url="https://github.com/yasakei/neutron-rs"
license=('custom:NPL-1.1')
# libc and libgcc_s are deliberately not bundled (a foreign libc breaks the
# binary); they come from these always-present base packages. LLVM, libstdc++
# and the rest of the closure ship inside /usr/lib/ntsc.
depends=('glibc' 'gcc-libs')
options=('!strip' '!debug' '!zipman' 'staticlibs')
source=("ntsc-$pkgver-linux-@ARCH@.tar.gz")
sha256sums=('SKIP')

package() {
  cd "$srcdir/ntsc-$pkgver-linux-@ARCH@"
  # bin/ntsc -> /usr/bin/ntsc, lib/ntsc/* -> /usr/lib/ntsc/*. The binary's
  # RUNPATH ($ORIGIN/../lib/ntsc) and ntsc's own runtime lookup (../lib/ntsc)
  # both resolve to /usr/lib/ntsc from /usr/bin, so LLVM and the runtime
  # archive are found with no further configuration.
  install -Dm755 bin/ntsc "$pkgdir/usr/bin/ntsc"
  install -Dm755 bin/ntsc-pkg "$pkgdir/usr/bin/ntsc-pkg"
  install -d "$pkgdir/usr/lib/ntsc"
  cp -a lib/ntsc/. "$pkgdir/usr/lib/ntsc/"
  install -Dm644 share/man/man1/ntsc.1.gz "$pkgdir/usr/share/man/man1/ntsc.1.gz"
  install -Dm644 LICENSE "$pkgdir/usr/share/licenses/ntsc/LICENSE"
}
PKGBUILD_EOF
sed -i "s/@VERSION@/$VERSION/g; s/@ARCH@/$ARCH/g" "$BUILD/PKGBUILD"

# PKGDEST/SRCDEST default to the PKGBUILD directory; --nodeps because the base
# runtime deps are always present and this only repackages a prebuilt tree.
( cd "$BUILD" && makepkg -f --nodeps )

PKG="$(find "$BUILD" -maxdepth 1 -name '*.pkg.tar.*' -print -quit)"
if [ -z "$PKG" ]; then
  echo "error: makepkg produced no package" >&2
  exit 1
fi
mv -f "$PKG" "dist/$(basename "$PKG")"
rm -rf "$BUILD"
echo "Built dist/$(basename "$PKG")"
