[package]
name = "ntsc-typeck"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Type checker for the NTSC (Neutron Type-Safe Compiler) language"

[dependencies]
ntsc-ast = { path = "../ntsc-ast" }
ntsc-diag = { path = "../ntsc-diag" }

[dev-dependencies]
ntsc-lexer = { path = "../ntsc-lexer" }
ntsc-parser = { path = "../ntsc-parser" }
